vich_uploader:
    db_driver: orm

    mappings:
        clients:
            uri_prefix: /images/clients
            upload_destination: "%kernel.project_dir%/public/images/clients"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
